/* Majlis — assessment question banks (data only). Loaded before app.js. */
const PHIL_QUESTIONS = [
  { q: 'A runaway train will kill five people unless you pull a lever that sends it onto a track where it will kill one person. What do you do?', opts: ['Pull the lever. Saving five is clearly better than saving one', 'Pull it, but I would feel guilty whichever way I went', 'Don\'t pull it. I shouldn\'t actively cause someone\'s death', 'There is no right answer. It just comes down to how people feel'] },
  { q: 'Your friend asks what you think of their business plan, which you expect to fail. Do you tell them the truth?', opts: ['Yes, always. Honesty matters more than feelings', 'Yes, but kindly and with suggestions', 'It depends on the friend and what\'s at stake', 'No. A kind white lie is better'] },
  { q: 'You find a wallet with $2,000 and an ID card. No one saw you pick it up. What do you do?', opts: ['Return it. It\'s the right thing whether or not anyone knows', 'Return it, mainly because of the kind of person I want to be', 'Return it, mostly because I would want mine back', 'Keep it. Nobody I know of gets hurt'] },
  { q: 'A well-run scientific study contradicts something you strongly believe. What do you do?', opts: ['Check the study\'s methods, and change my mind if they hold up', 'Take it seriously, but lean toward my existing view', 'Look for other studies that agree with me', 'Ignore it. I trust my own experience more'] },
  { q: 'A perfect copy of you is made and the original is painlessly destroyed. Is the copy still you?', opts: ['Yes. The copy has all the same memories and personality', 'Only if it carries on my thoughts without a break', 'No. It is a new person who thinks it\'s me', 'There\'s no fact of the matter'] },
  { q: 'Nobody can prove they aren\'t dreaming right now. How much does that bother you?', opts: ['Not at all. Reason tells me the world is real', 'A little, but everyday evidence is good enough', 'It bothers me. I can\'t be sure of much', 'I can\'t be sure of anything'] },
  { q: 'Someone says: "Morality is just opinion, so nothing is truly wrong." What\'s your reaction?', tag: 'morality', opts: ['They\'re wrong. Some things, like torture, are wrong whatever anyone thinks', 'Partly wrong. Morality is rooted in human nature but shaped by culture', 'Partly right. Morality changes a lot between cultures and eras', 'They\'re right. Morality is invented by people'] },
  { q: 'A criminal\'s brain scan shows his violent urges came from a childhood injury he didn\'t choose. Should he be punished like anyone else?', tag: 'freewill', opts: ['Yes. He still chose to act', 'Somewhat less, but he is still responsible', 'Much less. He was largely not in control', 'No. Nobody truly chooses their actions, so the idea of free will is incoherent'] },
  { q: 'Your doctor, a respected expert, recommends a treatment that your gut says is wrong. What do you do?', opts: ['Follow the expert. Gut feelings are unreliable', 'Follow the expert, but ask a lot of questions', 'Get a second opinion and weigh both', 'Trust my gut'] },
  { q: 'Two cultures disagree about something one sees as normal and the other as terrible. Can reason settle who is right?', opts: ['Yes. Reason can find the truth', 'Often, through shared human values and evidence', 'Sometimes, but some differences have no right answer', 'No. Each culture sets its own standards'] },
  { q: 'After you die, your brain stops working. What happens to your mind?', opts: ['It continues. The mind is more than the brain', 'It ends, but the mind was never just neurons', 'It ends. The mind is what the brain does', 'Nobody can know'] },
  { q: 'A friend holds a strong belief with no evidence, and it makes them happy. Is that okay?', opts: ['Yes. Some beliefs have to be taken on faith', 'Yes, as long as it harms nobody', 'Not really, but it\'s their right', 'No. Beliefs should follow the evidence'] },
  { q: 'A painting is praised by art experts, but you find it ugly. Who is right?', opts: ['The experts. Beauty has real standards', 'Both are partly right', 'Neither. It depends on your culture', 'I am. Beauty is personal taste'] },
  { q: 'Looking at the last few centuries, is the world getting better?', opts: ['Yes, clearly. Reason and morality have advanced', 'Mostly yes, with serious setbacks', 'Only technology improves', 'No. Things just change'] },
  { q: 'A man commits a crime, is truly remorseful, and is no danger to anyone. Should he still go to prison?', opts: ['Yes. He deserves to be punished', 'Yes, but for a shorter time', 'Probably not. Punishment should prevent future crime', 'No. The goal should be rehabilitation'] },
];

/* Religion: a top-level pick, then a short set of follow-up questions specific to
   that religion's real internal divisions, used to help the AI determine denomination/school. */
const RELIGIONS = [
  'Christianity','Islam','Judaism','Hinduism','Buddhism','Sikhism',
  "Bahá'í Faith",'Jainism','Taoism','Confucianism','Shinto','Zoroastrianism',
  'Paganism / Wicca','Atheism','Agnosticism','Spiritual but not religious','Other','Prefer not to say',
];

const RELIGION_QUESTIONS = {
  "Christianity": [{"q": "Which family of churches do you belong to or feel closest to?", "opts": ["Roman Catholic", "Eastern or Oriental Orthodox", "Mainline Protestant (Lutheran, Anglican, Reformed, Methodist, Presbyterian)", "Baptist, evangelical, Pentecostal or non-denominational"]}, {"q": "Who has the final say on what Christians must believe?", "opts": ["The Pope in Rome", "Councils of bishops, with no single pope", "The Bible alone, read by each believer", "My own church's leaders and statement of faith"]}, {"q": "What happens to the bread and wine at communion?", "opts": ["They become the actual body and blood of Christ (transubstantiation)", "Christ is truly present, but how is a mystery", "Christ is spiritually present for those who receive in faith", "It is a symbol that remembers Christ's death"]}, {"q": "Who should be baptized?", "opts": ["Infants, soon after birth", "Only believers who choose it for themselves, by full immersion", "Either babies or believers is fine", "Baptism is not required for salvation"]}, {"q": "How is a person saved?", "opts": ["By faith and good works, through the Church's sacraments", "By faith alone, as a free gift of God's grace", "By a personal \"born again\" decision to follow Jesus", "By God's choice before birth (predestination)"]}, {"q": "Who can be a priest or pastor?", "opts": ["Only men, and priests do not marry", "Only men, but they may be married", "Men and women", "Any believer the congregation recognises as called"]}, {"q": "How do you read the Bible?", "opts": ["Literally, word for word, including creation in six days", "Mostly literally, with some symbolism", "As inspired, but written by people in their own time", "Together with Church tradition and the writings of the Church Fathers"]}, {"q": "What do you think about praying to Mary and the saints?", "opts": ["I pray to Mary and the saints, and use rosaries or icons", "I honour Mary and the saints and use icons in worship", "I pray only to God", "I pray only through Jesus and avoid religious images"]}, {"q": "What is your usual Sunday service like?", "opts": ["A formal liturgy with set prayers, incense or vestments", "Scripture readings, a sermon and hymns", "Modern worship music and an informal sermon", "Spirit-led worship, with speaking in tongues or prayer for healing"]}, {"q": "Can a divorced person remarry in church?", "opts": ["No. Marriage lasts for life", "Only in some cases, with the church's approval", "Yes. It is a personal decision", "Yes, and I would not make it a church issue"]}],
  "Islam": [{"q": "Which branch of Islam do you follow?", "opts": ["Sunni", "Shia (Twelver)", "Shia (Ismaili or Zaydi)", "Ibadi, Ahmadiyya, or I am Muslim without a branch"]}, {"q": "Which school of Islamic law do you mostly follow?", "opts": ["Hanafi", "Maliki or Shafi'i", "Hanbali, or I go straight to the Quran and hadith (Salafi)", "Ja'fari (Shia) or I do not follow a school"]}, {"q": "How often do you pray the five daily prayers (salah)?", "opts": ["All five, every day, at their separate times", "Five prayers, combined into three sittings", "Some days, mostly Fridays and Eid", "Rarely or never"]}, {"q": "Who do you believe led the community after the Prophet Muhammad?", "opts": ["Abu Bakr and the first caliphs", "Ali and the twelve Imams", "Ali and a different line of Imams", "I don't see this as important to my faith"]}, {"q": "How do you view Sufism (mystical orders and visiting saints' tombs)?", "opts": ["I belong to a Sufi order (tariqa)", "I respect it but do not practise it", "I reject saint veneration as an innovation", "I have no strong view"]}, {"q": "How do you read the Quran and hadith?", "opts": ["Literally, following the hadith collections closely", "Through the classical scholars of my school", "With reason and historical context, in a reform-minded way", "The Quran alone, without hadith (Quranist)"]}, {"q": "What do you think about celebrating the Prophet's birthday (Mawlid)?", "opts": ["I celebrate it with gatherings and recitation", "It is allowed but I keep it simple", "It is a religious innovation and not allowed", "I have not thought about it"]}, {"q": "What role should Islamic law (sharia) have in government?", "opts": ["It should be the law of the state", "It should guide personal life while the state stays secular", "Only parts of it, such as family law", "I am not sure"]}, {"q": "How do you mark Ashura (10th of Muharram)?", "opts": ["Mourning Husayn with processions or majalis", "Fasting, remembering Moses' deliverance", "Both of these", "I do not mark it"]}, {"q": "Which best describes your practice?", "opts": ["Traditional and conservative", "Salafi or Wahhabi", "Modernist or progressive", "Mostly cultural, with limited practice"]}],
  "Judaism": [{"q": "Which movement are you part of?", "opts": ["Haredi or Hasidic Orthodox", "Modern Orthodox", "Conservative (Masorti)", "Reform, Reconstructionist or secular"]}, {"q": "How do you keep Shabbat?", "opts": ["No electricity, driving, cooking or handling money", "No work or driving, but flexible on some rules", "Candles and a Friday meal, and I drive to synagogue", "I do not mark it"]}, {"q": "How do you keep kosher?", "opts": ["Strictly, only certified products and separate dishes", "Kosher at home, flexible when eating out", "I only avoid pork and shellfish", "I do not keep kosher"]}, {"q": "What authority does Jewish law (halakha) have for you?", "opts": ["It is binding and cannot be changed", "It is binding but can develop through rabbis' rulings", "It is guidance, not a command", "It is my personal choice"]}, {"q": "Where did the Torah come from?", "opts": ["God gave it word for word to Moses at Sinai", "It is divinely inspired but written by people over time", "It is a human, historical text", "I am not sure"]}, {"q": "What is your view on women's role in services?", "opts": ["Men and women sit apart and only men lead", "Men and women may sit together but only men lead", "Full equality, including women rabbis and cantors", "I do not attend services"]}, {"q": "What do you believe about the Messiah?", "opts": ["A human descendant of King David will come and rebuild the Temple", "A future era of peace will come, with no individual messiah", "I do not believe in a messiah", "I am unsure"]}, {"q": "Do you follow a rebbe or a particular rabbi?", "opts": ["Yes, a Hasidic rebbe", "Yes, a rabbi from the Lithuanian yeshiva tradition", "I follow my local community rabbi", "No"]}, {"q": "What language do you pray in?", "opts": ["Hebrew only, from the traditional siddur", "Mostly Hebrew with some English", "Equal parts Hebrew and English", "Mostly English, or I rarely pray formally"]}, {"q": "Which of these do you observe?", "opts": ["Daily prayer three times a day, with tefillin", "Weekly synagogue attendance", "The High Holidays only", "Mostly cultural events like the Passover seder"]}],
  "Hinduism": [{"q": "Which deity or tradition is central to your worship?", "opts": ["Vishnu, Krishna or Rama (Vaishnavism)", "Shiva (Shaivism)", "The Goddess: Durga, Kali or Lakshmi (Shaktism)", "All deities equally (Smarta)"]}, {"q": "Which philosophy do you lean toward?", "opts": ["Advaita: everything is one Brahman", "Vishishtadvaita: God and souls are distinct but inseparable", "Dvaita: God and the soul are eternally separate", "I do not follow a particular school"]}, {"q": "Which text do you turn to most?", "opts": ["The Vedas and Upanishads", "The Bhagavad Gita", "The Ramayana, Mahabharata or Puranas", "The Agamas or Tantras"]}, {"q": "What is your daily worship like?", "opts": ["Puja at a home altar, with offerings and mantras", "Weekly temple visits", "Meditation and yoga", "Festivals and family occasions only"]}, {"q": "Do you follow a guru or movement?", "opts": ["A living guru or sampradaya", "A movement like ISKCON, Swaminarayan or Ramakrishna Mission", "Arya Samaj, which follows the Vedas alone", "No guru"]}, {"q": "What is your view on worshipping images (murti)?", "opts": ["God has form, and the image is truly God", "The image is a help toward the formless Brahman", "I reject idol worship", "I use both images and formless meditation"]}, {"q": "What do you eat?", "opts": ["Strict vegetarian, no eggs", "Vegetarian with dairy and eggs", "I eat meat but never beef", "No restrictions"]}, {"q": "What is the best path to liberation (moksha)?", "opts": ["Devotion to God (bhakti)", "Knowledge and self-inquiry (jnana)", "Selfless action and duty (karma yoga)", "Meditation and discipline (raja yoga)"]}, {"q": "Which festival is most important to you?", "opts": ["Diwali", "Navaratri or Durga Puja", "Maha Shivaratri", "Janmashtami, Ram Navami or Holi"]}, {"q": "What do you believe about rebirth?", "opts": ["I will be reborn until I achieve moksha", "Rebirth happens but I focus on this life", "It is a symbolic teaching", "I am unsure"]}],
  "Buddhism": [{"q": "Which tradition of Buddhism are you in?", "opts": ["Theravada (Thailand, Sri Lanka, Myanmar)", "Zen or Chan", "Pure Land or Nichiren", "Tibetan (Vajrayana)"]}, {"q": "What is your main goal?", "opts": ["Personal liberation, becoming an arhat", "Becoming a bodhisattva to free all beings", "Rebirth in the Pure Land of Amitabha", "Full Buddhahood in this lifetime through tantric practice"]}, {"q": "What is your main practice?", "opts": ["Insight meditation (vipassana) and mindfulness", "Seated meditation (zazen) or koans", "Chanting, such as Nam Amida Butsu or Nam Myoho Renge Kyo", "Mantras, visualisation and deity practice"]}, {"q": "Which texts do you rely on most?", "opts": ["The Pali Canon", "Mahayana sutras like the Heart or Lotus Sutra", "Tibetan texts and the teachings of lamas", "No single text, mainly my teacher's words"]}, {"q": "What do you believe about rebirth?", "opts": ["I will be reborn according to my karma", "It is symbolic of how states of mind change", "I do not believe in rebirth", "I am unsure"]}, {"q": "How are you involved with Buddhism?", "opts": ["I am an ordained monk or nun", "A lay follower who supports a temple or sangha", "I practise meditation on my own", "I study the teachings without formal practice"]}, {"q": "Do you pray to or make offerings to Buddhas and bodhisattvas?", "opts": ["Yes, to Amitabha, Avalokiteshvara or Tara", "I make offerings to the Buddha as a sign of respect", "No, the Buddha is a teacher and not a deity", "I rarely do"]}, {"q": "How does enlightenment come?", "opts": ["Gradually, through ethics, meditation and wisdom", "Suddenly, in a moment of direct insight", "Through the grace of Amitabha", "I do not think about enlightenment"]}, {"q": "What is your relationship with a teacher?", "opts": ["I follow a lama and receive empowerments", "I practise under a Zen master or monk", "I follow a monastery in the forest tradition", "I have no teacher"]}, {"q": "What is your diet?", "opts": ["Vegetarian or vegan", "Vegetarian when possible", "I eat meat if it was not killed for me", "No restrictions"]}],
  "Sikhism": [{"q": "Are you an initiated Sikh (Amritdhari)?", "opts": ["Yes, I took Amrit and follow the Rehat Maryada", "I keep uncut hair but have not taken Amrit", "I am learning and adopting Sikhism gradually", "I follow Sikhism mostly culturally"]}, {"q": "Which of the Five Ks do you keep?", "opts": ["All five: kesh, kangha, kara, kachera and kirpan", "Most of them", "Mainly uncut hair and a turban", "Mainly the kara"]}, {"q": "Which scripture is your authority?", "opts": ["The Guru Granth Sahib alone", "The Guru Granth Sahib and the Dasam Granth", "The Guru Granth Sahib and teachings of a living guru or sant", "The Guru Granth Sahib and the writings of Bhai Gurdas"]}, {"q": "What do you eat?", "opts": ["Strict vegetarian", "No meat from ritual (kutha) slaughter", "Meat is allowed", "No restrictions"]}, {"q": "Which daily prayers do you recite?", "opts": ["The five Nitnem banis, including Japji Sahib", "Japji Sahib and a few others", "I attend gurdwara but rarely recite", "I rarely pray"]}, {"q": "How often do you visit a gurdwara?", "opts": ["Daily or most days", "Weekly", "On festivals like Vaisakhi and Gurpurab", "Rarely"]}, {"q": "What do you think about caste in Sikhism?", "opts": ["There is no caste and I reject it in marriage and community", "There is no caste in theory but it still shapes my community", "It is a social tradition I follow", "I have not thought about it"]}, {"q": "What is your view on the Khalsa and the military tradition?", "opts": ["The Khalsa is central to who I am", "I respect it but follow the Gurus' message of devotion", "I follow a sant or Sant Mat tradition instead", "I keep to the Guru Granth Sahib without a particular movement"]}],
  "Bah\u00e1'\u00ed Faith": [{"q": "Do you recite the obligatory daily prayer?", "opts": ["Yes, one of the three obligatory prayers every day", "I say prayers daily but not always the obligatory one", "I pray occasionally", "Rarely"]}, {"q": "Do you keep the Nineteen Day Fast (2 to 20 March)?", "opts": ["Yes, fully", "I keep it with exceptions for health", "I observe a lighter version", "No"]}, {"q": "Do you attend the Nineteen Day Feast?", "opts": ["Yes, every Feast", "Most Feasts", "Occasionally", "Rarely"]}, {"q": "Who do you regard as the central authority?", "opts": ["The Universal House of Justice in Haifa", "Local and National Spiritual Assemblies", "The Writings of Bahá'u'lláh and Abdu'l-Bahá", "I am not enrolled and follow the faith informally"]}, {"q": "How do you see the other religions?", "opts": ["All are from one God, and each Manifestation progressively revealed the same truth", "They are all true but Bahá'u'lláh is the latest", "I respect them but follow the Bahá'í teachings", "I do not think about it"]}, {"q": "What do you think about alcohol and drugs?", "opts": ["I avoid them completely", "I avoid them mostly", "Allowed in moderation", "I have no rule"]}, {"q": "What is your view on pilgrimage?", "opts": ["I have gone or plan to go to the Shrines in Haifa and Akka", "I would like to go one day", "I am not planning to", "It does not matter to me"]}, {"q": "What is most important to you?", "opts": ["The unity of humanity", "Service to my community", "Equality of men and women", "Harmony of science and religion"]}],
  "Jainism": [{"q": "Which tradition are you in?", "opts": ["Digambara", "Svetambara Murtipujaka", "Svetambara Sthanakvasi or Terapanthi", "I follow Jainism without a branch"]}, {"q": "What do you believe about nudity of monks?", "opts": ["Monks should be fully nude (Digambara)", "Monks wear white robes (Svetambara)", "It does not matter", "I have no view"]}, {"q": "What about worshipping images of Tirthankaras?", "opts": ["I worship images in a temple", "I do not worship images and meditate instead", "I do both", "I rarely worship"]}, {"q": "Can women attain liberation (moksha) in this life?", "opts": ["Yes, as men do", "Not directly, first as a man", "I am unsure", "I have no view"]}, {"q": "What do you eat?", "opts": ["Strict Jain: no root vegetables, honey, or eating after sunset", "Vegetarian, avoiding onion and garlic", "Vegetarian", "No restrictions"]}, {"q": "Do you fast during Paryushana?", "opts": ["Yes, for several days or more", "Yes, for a day or two", "I observe a light fast", "No"]}, {"q": "What guides your day-to-day life most?", "opts": ["Ahimsa: avoiding harm to any living thing", "Aparigraha: not holding on to possessions", "Anekantavada: seeing many sides of truth", "All three equally"]}, {"q": "Which scriptures do you follow?", "opts": ["The Agamas", "The Tattvartha Sutra", "Digambara texts such as the Shatkhandagama", "I follow my community's teaching"]}],
  "Taoism": [{"q": "Which side of Taoism do you follow?", "opts": ["Philosophical: the Tao Te Ching and Zhuangzi", "Religious: temples, priests and deities", "Both", "I follow Taoist ideas without a label"]}, {"q": "Which lineage are you closest to?", "opts": ["Zhengyi (Celestial Masters)", "Quanzhen (Complete Perfection)", "A folk or local Chinese tradition", "None in particular"]}, {"q": "Which practices do you do?", "opts": ["Meditation and inner alchemy (neidan)", "Tai chi or qigong", "Rituals, talismans and offerings", "Reading and reflecting on the texts"]}, {"q": "Do you worship Taoist deities?", "opts": ["Yes, the Jade Emperor and other gods", "I honour ancestors and local gods", "I see them as symbols", "No"]}, {"q": "Which Taoist text do you read most?", "opts": ["The Tao Te Ching", "The Zhuangzi", "Ritual manuals and the Daozang canon", "The I Ching"]}, {"q": "How do you view immortality?", "opts": ["Spiritual immortality through cultivation", "Symbolic, living in harmony", "It is not a goal for me", "I am unsure"]}, {"q": "Which festival matters most to you?", "opts": ["Chinese New Year and Lantern Festival", "Birthdays of Taoist gods", "Qingming, honouring ancestors", "I do not follow festivals"]}, {"q": "Do you use feng shui or divination (I Ching)?", "opts": ["Both regularly", "The I Ching", "Feng shui", "Neither"]}],
  "Confucianism": [{"q": "How do you follow Confucianism?", "opts": ["As a way of life and ethics", "As a religion with rituals", "As a tradition of scholarship", "Mainly through family culture"]}, {"q": "Do you honour your ancestors with rituals?", "opts": ["Yes, regularly at home or a family shrine", "At Qingming or other main festivals", "Occasionally", "No"]}, {"q": "Which text do you value most?", "opts": ["The Analects", "Mencius", "The Great Learning or the Doctrine of the Mean", "Neo-Confucian writings, such as those of Zhu Xi"]}, {"q": "What is human nature, in your view?", "opts": ["Naturally good, as Mencius taught", "Naturally selfish and needing education, as Xunzi taught", "Neutral and shaped by upbringing", "I do not take a view"]}, {"q": "Which virtue do you consider most important?", "opts": ["Ren (benevolence)", "Li (propriety and ritual)", "Xiao (filial piety)", "Yi (righteousness)"]}, {"q": "What role should a ruler play?", "opts": ["A virtuous example the people follow", "An official chosen by merit", "A guardian of tradition", "I have no view"]}, {"q": "Do you attend a Confucian temple?", "opts": ["Yes, for ceremonies such as Confucius's birthday", "Occasionally", "I visit as a tourist", "No"]}, {"q": "How do you view family duty?", "opts": ["Obedience and care for parents above all", "Care and respect, with room to disagree", "A balance with personal goals", "It is a cultural habit"]}],
  "Shinto": [{"q": "How do you practise Shinto?", "opts": ["I visit a local shrine regularly", "At New Year and major festivals", "At life events like weddings and shichi-go-san", "At home with a kamidana altar"]}, {"q": "Which kami do you feel closest to?", "opts": ["Amaterasu and the imperial ancestors", "The local deity of my area (ujigami)", "Inari, Hachiman or another popular kami", "Nature spirits in mountains, rivers and trees"]}, {"q": "Which type of Shinto do you follow?", "opts": ["Shrine Shinto", "Sect Shinto (e.g. Tenrikyo, Konkokyo)", "Folk Shinto", "State or imperial Shinto traditions"]}, {"q": "What do you do at a shrine?", "opts": ["Purify hands and mouth, bow twice, clap twice, bow once", "Make an offering and a wish", "Buy omamori (amulets) or draw omikuji", "Mostly look around"]}, {"q": "Do you attend matsuri (festivals)?", "opts": ["Yes, I help carry the mikoshi or organise", "Yes, I attend", "Occasionally", "No"]}, {"q": "How do you relate Shinto to Buddhism?", "opts": ["I practise both, Shinto for life and Buddhism for death", "Mostly Shinto", "Mostly Buddhism", "I keep them separate"]}, {"q": "What is purity (harae) for you?", "opts": ["A ritual to remove impurity before worship", "A way of life, keeping clean and honest", "A symbolic idea", "I do not think about it"]}, {"q": "Do you travel to Ise or other great shrines?", "opts": ["Yes, on pilgrimage", "I would like to", "Rarely", "No"]}],
  "Zoroastrianism": [{"q": "Which community are you from?", "opts": ["Parsi (India)", "Irani (Iran)", "Western diaspora", "A convert or I have no community"]}, {"q": "Do you visit a fire temple?", "opts": ["Yes, regularly", "On festivals", "Occasionally", "No"]}, {"q": "Do you wear the sudreh and kusti?", "opts": ["Yes, daily, and I tie the kusti when praying", "Only at ceremonies", "I have them but rarely use them", "No"]}, {"q": "What is your view on conversion?", "opts": ["Only people born to Zoroastrian parents can be Zoroastrian", "Children of a Zoroastrian father only", "Anyone who sincerely accepts the faith can join", "I am not sure"]}, {"q": "What do you believe about good and evil?", "opts": ["Ahura Mazda is the one wise God, and evil (Angra Mainyu) is not equal to him", "Dualism: good and evil are two forces", "A moral choice, with free will", "I see them as symbols"]}, {"q": "Which calendar do you follow?", "opts": ["Shahenshahi", "Qadimi", "Fasli", "I do not follow a specific one"]}, {"q": "What do you think about funerals?", "opts": ["Tower of Silence (dokhma)", "Burial or cremation is acceptable", "I am unsure", "I have no strong view"]}, {"q": "Which text do you recite?", "opts": ["The Gathas of Zarathustra", "The Avesta in Avestan", "Prayers in Gujarati or Persian", "None regularly"]}],
  "Paganism / Wicca": [{"q": "Which path do you follow?", "opts": ["Wicca (Gardnerian, Alexandrian or eclectic)", "Heathenry or Norse (Asatru)", "Druidry or Celtic", "Hellenic, Kemetic or another reconstructionist path"]}, {"q": "Do you practise alone or in a group?", "opts": ["Solitary", "In a coven or kindred", "Both", "Occasionally join public rituals"]}, {"q": "How do you see the gods?", "opts": ["As distinct individual beings (hard polytheism)", "As aspects of one Goddess and God", "As archetypes or symbols", "I am still deciding"]}, {"q": "Which festivals do you celebrate?", "opts": ["The eight Wiccan sabbats", "Norse feasts like Yule and blóts", "Seasonal Celtic festivals like Samhain and Beltane", "Greek or Egyptian festivals"]}, {"q": "Do you practise magic?", "opts": ["Yes, ritual magic with tools and spells", "Yes, small intention-setting", "Mainly devotion, not magic", "No"]}, {"q": "Do you work with the moon?", "opts": ["Yes, esbats at full moons", "Occasionally", "I follow the solar year", "No"]}, {"q": "What is your relation to nature?", "opts": ["Nature is sacred, and I honour land spirits", "I do outdoor rituals", "I connect through gardens or herbs", "Mostly symbolic"]}, {"q": "Which ethic guides you?", "opts": ["The Wiccan Rede: harm none", "The Nine Noble Virtues", "Honour to the gods and ancestors", "My own conscience"]}],
  "Atheism": [{"q": "Which best describes your atheism?", "opts": ["I am sure there are no gods (strong atheism)", "I do not believe, but I do not claim certainty (weak atheism)", "I reject specific gods but remain open on others", "I do not use labels, I just do not believe"]}, {"q": "How do you view religion?", "opts": ["It is harmful and should be challenged (anti-theist)", "It is wrong but I am tolerant of believers", "It has good and bad effects", "I am indifferent"]}, {"q": "What is your main reason for not believing?", "opts": ["No convincing evidence", "The problem of evil", "Science explains the world without gods", "I was never religious"]}, {"q": "Where do your morals come from?", "opts": ["Reason and secular humanism", "Evolution and human empathy", "Law and social contract", "Personal conscience"]}, {"q": "How do you mark weddings and funerals?", "opts": ["Secular or humanist ceremonies", "Civil ceremony only", "I attend religious ones out of respect", "I do not mark them"]}, {"q": "Do you celebrate Christmas or other religious holidays?", "opts": ["As cultural holidays", "I avoid them", "I celebrate the season and family only", "Yes, with religious relatives"]}, {"q": "What happens after death?", "opts": ["Nothing: consciousness ends", "I live on through memory and impact", "I am unsure but expect nothing", "I do not think about it"]}, {"q": "Church and state?", "opts": ["Strict separation, no religion in public life", "Mostly separate with tolerance", "Religion can have some public role", "I have no strong view"]}],
  "Agnosticism": [{"q": "Which best describes your agnosticism?", "opts": ["It is impossible to know whether gods exist", "I personally don't know, but others may", "The question of God is meaningless", "I do not care either way (apatheism)"]}, {"q": "Do you lean toward belief or disbelief?", "opts": ["I lean toward belief", "I lean toward disbelief", "I am evenly balanced", "I do not lean either way"]}, {"q": "Do you ever pray?", "opts": ["Yes, in a crisis, just in case", "I meditate instead", "No", "I do not know"]}, {"q": "What evidence would change your mind?", "opts": ["A clear, verifiable sign", "Strong philosophical arguments", "A personal experience", "Nothing, the question cannot be settled"]}, {"q": "How do you view religious people?", "opts": ["They may be right, and I respect their path", "They are sincere but I cannot share it", "They have a comfort I lack", "I do not judge"]}, {"q": "Where do your morals come from?", "opts": ["Reason and empathy", "Upbringing and culture", "Philosophy", "A mix"]}, {"q": "Do you attend religious services?", "opts": ["Sometimes, to explore", "Only for family events", "Never", "I used to"]}, {"q": "What would you tell your children?", "opts": ["Let them explore all views", "Raise them without religion", "Raise them in a religion for culture", "I have not decided"]}],
  "Spiritual but not religious": [{"q": "How would you describe your spirituality?", "opts": ["A sense of connection with the universe", "A personal relationship with a higher power", "Mindfulness and inner peace", "Nature as sacred"]}, {"q": "Which practices do you do?", "opts": ["Meditation or yoga", "Astrology or tarot", "Crystals or energy healing", "Time in nature"]}, {"q": "What do you think about God?", "opts": ["God is the universe itself", "An impersonal energy or consciousness", "A loving presence", "I am still exploring"]}, {"q": "Do you borrow from established religions?", "opts": ["Yes, from several, such as Buddhism and Hinduism", "Mostly from Christianity, but not its institutions", "I make my own path", "I avoid organised religion"]}, {"q": "What do you believe about reincarnation?", "opts": ["I will be reborn", "Souls continue in some form", "I am unsure", "I do not believe in it"]}, {"q": "Do you believe in a soul?", "opts": ["Yes, an eternal soul", "A spirit that connects us all", "A symbolic idea", "No"]}, {"q": "Why not organised religion?", "opts": ["Too many rules and dogma", "Hypocrisy in institutions", "I want to find my own truth", "I do not need it"]}, {"q": "How do you find meaning?", "opts": ["Through love and relationships", "Through service to others", "Through creativity and art", "Through nature and wonder"]}],
};

/* Compass sections: specific agree/disagree statements about one concrete proposal each, like most online tests.
   dir = +1 means agreeing pushes toward the high end of the axis (Right, Laissez-faire, Globalist,
   Libertarian, Progressive, Individualist); -1 means agreeing pushes toward the low end. */
const LIKERT = ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'];
const ECON_X_QUESTIONS = [
  { q: 'Households earning over $500,000 a year should pay at least half of their income in tax.', dir: -1, opts: LIKERT },
  { q: 'The government should run one public health insurance system that covers everyone.', dir: -1, opts: LIKERT },
  { q: 'The minimum wage should be abolished, leaving pay to be agreed between workers and employers.', dir: 1, opts: LIKERT },
  { q: 'Companies with over 500 employees should be required to give workers seats on their board.', dir: -1, opts: LIKERT },
  { q: 'Unemployment benefits should stop after six months so people look for work faster.', dir: 1, opts: LIKERT },
  { q: 'Inheritances over $2 million should be taxed at 50% or more.', dir: -1, opts: LIKERT },
  { q: 'The corporate tax rate should be cut to attract investment, even if government spending falls.', dir: 1, opts: LIKERT },
  { q: 'State pensions should be replaced with private retirement accounts that each person controls.', dir: 1, opts: LIKERT },
  { q: 'The government should guarantee every adult a basic income, paid for by higher taxes.', dir: -1, opts: LIKERT },
  { q: 'Billionaires\' wealth should be taxed every year, even if they have not sold anything.', dir: -1, opts: LIKERT },
  { q: 'Free-market competition, not government programmes, is the best way to lift people out of poverty.', dir: 1, opts: LIKERT },
  { q: 'Trade unions have too much power and slow down the economy.', dir: 1, opts: LIKERT },
];
const ECON_Y_QUESTIONS = [
  { q: 'The government should cap rents in big cities.', dir: -1, opts: LIKERT },
  { q: 'Airlines, railways and energy companies should be privately owned.', dir: 1, opts: LIKERT },
  { q: 'The government should put tariffs on cheap imports to protect factories at home.', dir: -1, opts: LIKERT },
  { q: 'The government should let a failing major bank collapse instead of bailing it out.', dir: 1, opts: LIKERT },
  { q: 'The state should own the major banks and energy companies.', dir: -1, opts: LIKERT },
  { q: 'Occupational licences, such as for hairdressers and tour guides, should mostly be scrapped.', dir: 1, opts: LIKERT },
  { q: 'The government should use public money to subsidise green energy and electric cars.', dir: -1, opts: LIKERT },
  { q: 'Companies should be free to set their own prices and working conditions with minimal government rules.', dir: 1, opts: LIKERT },
  { q: 'During a crisis, the government should set maximum prices for essentials such as bread, fuel and electricity.', dir: -1, opts: LIKERT },
  { q: 'Taxis, ride-share and short-term rentals should be allowed to operate without city licences.', dir: 1, opts: LIKERT },
  { q: 'The state should run a national plan for key sectors such as steel, microchips and shipbuilding.', dir: -1, opts: LIKERT },
  { q: 'Free-trade deals that remove tariffs should be signed with as many countries as possible.', dir: 1, opts: LIKERT },
];
const POL_X_QUESTIONS = [
  { q: 'My country should leave international organisations like the UN or the WTO if they limit its freedom to act.', dir: -1, opts: LIKERT },
  { q: 'Anyone with a job offer should be allowed to move to my country to work.', dir: 1, opts: LIKERT },
  { q: 'International courts should be able to overrule my country\'s laws on human rights.', dir: 1, opts: LIKERT },
  { q: 'Immigration should be cut sharply to protect jobs and national identity.', dir: -1, opts: LIKERT },
  { q: 'My country should hand some independence to a larger body, like the EU, to solve shared problems.', dir: 1, opts: LIKERT },
  { q: 'Foreign companies should be banned from buying key national industries such as ports and energy.', dir: -1, opts: LIKERT },
  { q: 'Rich countries should accept refugees even when it is costly.', dir: 1, opts: LIKERT },
  { q: 'Schools should give priority to teaching the national language, history and culture over other cultures.', dir: -1, opts: LIKERT },
];
const POL_Y_QUESTIONS = [
  { q: 'Police should be allowed to read a suspect\'s private messages without a court order.', dir: -1, opts: LIKERT },
  { q: 'People should be allowed to publish any opinion, even hateful ones.', dir: 1, opts: LIKERT },
  { q: 'Anyone convicted of a violent crime should get a long prison sentence with no early release.', dir: -1, opts: LIKERT },
  { q: 'Cannabis and other recreational drugs should be legal for adults.', dir: 1, opts: LIKERT },
  { q: 'The government should be able to ban protests it considers disruptive.', dir: -1, opts: LIKERT },
  { q: 'Facial-recognition cameras should be allowed in public places to catch criminals.', dir: -1, opts: LIKERT },
  { q: 'Citizens should be allowed to carry firearms with few restrictions.', dir: 1, opts: LIKERT },
  { q: 'Apps and companies should be allowed to use encryption that police cannot break.', dir: 1, opts: LIKERT },
];
const SOC_X_QUESTIONS = [
  { q: 'Same-sex couples should have exactly the same marriage rights as everyone else.', dir: 1, opts: LIKERT },
  { q: 'Abortion should be legal for any reason in the first 12 weeks of pregnancy.', dir: 1, opts: LIKERT },
  { q: 'Prayer or religious teaching should be part of daily life in public schools.', dir: -1, opts: LIKERT },
  { q: 'Schools should teach students about different gender identities and sexual orientations.', dir: 1, opts: LIKERT },
  { q: 'Divorce should be harder to get when a couple has young children.', dir: -1, opts: LIKERT },
  { q: 'Public holidays should centre on the country\'s traditional religion.', dir: -1, opts: LIKERT },
  { q: 'Children should be expected to follow their parents\' religion.', dir: -1, opts: LIKERT },
  { q: 'People should be able to change their gender on official documents on request.', dir: 1, opts: LIKERT },
];
const SOC_Y_QUESTIONS = [
  { q: 'A person should be free to leave their family\'s religion or career path without it being treated as shameful.', dir: 1, opts: LIKERT },
  { q: 'Vaccines should be required to attend school or work during an outbreak.', dir: -1, opts: LIKERT },
  { q: 'Adults should be free to live however they like, as long as they harm no one else.', dir: 1, opts: LIKERT },
  { q: 'Every young person should do a year of national service, military or civilian.', dir: -1, opts: LIKERT },
  { q: 'Adult children should be expected to look after their elderly parents instead of relying on the state.', dir: -1, opts: LIKERT },
  { q: 'Neighbours should be able to set shared community rules, like noise and house appearance, even if some residents object.', dir: -1, opts: LIKERT },
  { q: 'A person should be able to refuse a medical treatment even if it puts others at small risk.', dir: 1, opts: LIKERT },
  { q: 'Terminally ill adults should be allowed to choose assisted dying.', dir: 1, opts: LIKERT },
];
const ECONOMIC_QUESTIONS = ECON_X_QUESTIONS.map(q=>({...q, axis:'x'})).concat(ECON_Y_QUESTIONS.map(q=>({...q, axis:'y'})));
const POLITICAL_QUESTIONS = POL_X_QUESTIONS.map(q=>({...q, axis:'x'})).concat(POL_Y_QUESTIONS.map(q=>({...q, axis:'y'})));
const SOCIAL_QUESTIONS = SOC_X_QUESTIONS.map(q=>({...q, axis:'x'})).concat(SOC_Y_QUESTIONS.map(q=>({...q, axis:'y'})));
